name: Terraform Apply

on:
  workflow_dispatch: # manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515271328:role/PipelineRole
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Lambda package
        run: |
          cd lambda
          pip install psycopg2-binary -t .
          zip -r signup.zip .

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload website to S3
        run: aws s3 cp index.html s3://mythirdspace-website-prod/index.html

      - name: Invalidate CloudFront cache
        run: |
          DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"