name: Terraform Plan

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515271328:role/PipelineRole
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Lambda package
        run: |
          cd lambda
          pip install psycopg2-binary -t .
          zip -r signup.zip .

      - name: Terraform Plan
        run: terraform plan