name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write # allows GitHub to generate an OIDC JWT token for the workflow
  contents: read # Allows the workflow to read your repository contents

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515271328:role/github_oidc_terraform-aws-website
          aws-region: eu-west-2

      - name: Test identity
        run: |
          aws sts get-caller-identity
          aws s3 ls
